import type { Metadata } from 'next'
import '@/styles/main.scss'
import 'helix-color'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode
}>) => {
	return (
		<html lang='pt-BR'>
			<body>{children}</body>
		</html>
	)
}

export default RootLayout
