import type { Metadata } from 'next'
import '@/styles/main.scss'
import 'helix-color'
import { Header } from '@/components/Header'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode
}>) => {
	return (
		<html lang='pt-BR'>
			<head>
				<link rel='icon' href='/favicon.png' sizes='any' />
			</head>
			<body className='bg-light-primary'>
				<Header />
				{children}
			</body>
		</html>
	)
}

export default RootLayout
